version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bse
      MYSQL_ROOT_PASSWORD: Qwertyuiop7502755701
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    #command: uvicorn app.api.endpoints:app --reload --host 127.0.0.1 --port 8000
    ports:
      - 8111:8111
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=Qwertyuiop7502755701
      - DB_DATABASE=bse
    volumes:
      - ./app:/app/app  # Mount the app code to the container
    restart: always

volumes:
  mysql-data:
